---
functional:
  - 1) Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - 2) Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - 3) Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
non-functional:
  - 1) Сайт должен иметь мобильную версию.
  - 2) Сайт должен быть способен обрабатывать большое количество трафика.
  - 3) Сайт должен быть протестирован на совместимость с последними версиями браузеров.
implicit:
  - 1) Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д. 
  # НЕзавершенность : Указана лишь часть некоторого перечисления.
  
  - 2) Сайт должен быть доступен на различных устройствах.
  # НЕоднозначность : Использование терминов или фраз, допускающих субъективное толкование.
  
  - 3) Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  # НЕоднозначность : Использование терминов или фраз, допускающих субъективное толкование.

  - 4) Сайт должен быть безопасным и защищать данные пользователя.
  # НЕзавершенность : Отсутствуют нефункциональные составляющие требования.

  # (общее) Прослеживаемость : Требования не пронумерованы, не структурированы, не имеют оглавления, не имеют работающих перекрёстных ссылок.
# Добавление требований : Пользователь имеет возможность купить товары.
